In [30]:
a = 10
a

10

In [31]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [32]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)


[5 7 9]


In [4]:
a = np.array([1,2,3])
type(a)
a.shape

(3,)

In [5]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
#even numbers
np.arange(2,102,2)


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [7]:
import numpy as np 
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(2,3)

array([[0.80666539, 0.89113581, 0.27021482],
       [0.91956686, 0.479421  , 0.13247206]])

In [12]:
np.random.randint(2,6)

4

In [13]:
np.random.randn(2,3)

array([[ 0.68322737,  1.22726795,  1.20753769],
       [-0.14936948,  0.91812986, -0.5642523 ]])

In [14]:
np.random.randint(2,6,size = (2,3))

array([[3, 4, 4],
       [3, 5, 5]], dtype=int32)

In [15]:
a.shape
b = np.array([[[1,2,3],[3,4,5]]])
#b.ndim

In [16]:
b.reshape(1,-1)
b.reshape(-1,1)

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [17]:
b.flatten()

array([1, 2, 3, 3, 4, 5])

In [18]:
c=np.array([[2,3],[4,5]])
c1 = c.flatten()
c1[0] = 8
print(c)
print(c1)

[[2 3]
 [4 5]]
[8 3 4 5]


In [19]:
import numpy as np
c=np.array([[2,3],[4,5]])
c1 = c.ravel()
c1[0] = 8
print(c)
print(c1)

[[8 3]
 [4 5]]
[8 3 4 5]


In [20]:
import numpy as np
d = np.array([[[1,4,6,7],[2,9,56,3]],[[2,34,78,1],[8,4,32,6]]])
print(d[1][1][2])
print(d[:,1])
print(d[1:4]) 
d[d>10]


32
[[ 2  9 56  3]
 [ 8  4 32  6]]
[[[ 2 34 78  1]
  [ 8  4 32  6]]]


array([56, 34, 78, 32])

In [21]:
#aggregations means adding 
np.sum(d)

np.int64(253)

In [22]:
np.sum(d,axis=0)    # column wise 

array([[ 3, 38, 84,  8],
       [10, 13, 88,  9]])

In [23]:
np.sum(d,axis=1)  # row wise


array([[  3,  13,  62,  10],
       [ 10,  38, 110,   7]])

In [24]:
np.random.seed(42)
np.random.normal(3,1)

3.496714153011233

In [25]:
np.argsort(d)

array([[[0, 1, 2, 3],
        [0, 3, 1, 2]],

       [[3, 0, 1, 2],
        [1, 3, 0, 2]]])

In [26]:
np.sort(d)

array([[[ 1,  4,  6,  7],
        [ 2,  3,  9, 56]],

       [[ 1,  2, 34, 78],
        [ 4,  6,  8, 32]]])

In [27]:
np.vstack(d)


array([[ 1,  4,  6,  7],
       [ 2,  9, 56,  3],
       [ 2, 34, 78,  1],
       [ 8,  4, 32,  6]])

In [28]:
np.hstack(d)

array([[ 1,  4,  6,  7,  2, 34, 78,  1],
       [ 2,  9, 56,  3,  8,  4, 32,  6]])

In [29]:
d

array([[[ 1,  4,  6,  7],
        [ 2,  9, 56,  3]],

       [[ 2, 34, 78,  1],
        [ 8,  4, 32,  6]]])

In [46]:
#broadcasting 
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = np.array([1,2,3])
result = x+y
print(result)
#np.shape(a)

[[2 4 6]
 [5 7 9]]
